services:
  test:
    build: .
    #image
    image: ghcr.io/zhanhong-msu/test:latest
    container_name: test
    volumes:
      - ..:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true
